### ISSUE TITLE
mob_multi_graph.npy

### ISSUE THREAD

**Issue by eugenia-cell** [wushangbin/MGFN#3]
您好，数据集部分没有mob_multi_graph.npy文件呢，能否麻烦上传一下？

**Comment by wushangbin** [comment]
这个文件太大了，所以没上传

**Comment by eugenia-cell** [comment]
那能不能请问下这个轨迹数据具体是哪年哪个月的，是yellow taxi trip 还是green taxi trip呀？我在nyc open data上搜出来很多结果我不知道具体选择哪个。或者您能分享一下最原始轨迹数据集的下载链接么，麻烦了~  万分感谢！！！
________________________________
发件人: wushangbin ***@***.***>
发送时间: 2024年4月25日 4:27
收件人: wushangbin/MGFN ***@***.***>
抄送: eugenia-cell ***@***.***>; Author ***@***.***>
主题: Re: [wushangbin/MGFN] mob_multi_graph.npy (Issue #3)


这个文件太大了，所以没上传

―

**Comment by wushangbin** [comment]
我在另一个issue下也回复了，是2015年7月的数据，yellow和green都用了。 下载链接：https://opendata.cityofnewyork.us/

**Comment by eugenia-cell** [comment]
好的好的 非常感谢~
________________________________
发件人: wushangbin ***@***.***>
发送时间: 2024年4月25日 5:08
收件人: wushangbin/MGFN ***@***.***>
抄送: eugenia-cell ***@***.***>; Author ***@***.***>
主题: Re: [wushangbin/MGFN] mob_multi_graph.npy (Issue #3)


我在另一个issue下也回复了，是2015年7月的数据，yellow和green都用了。 下载链接：https://opendata.cityofnewyork.us/

―
