### ISSUE TITLE
请教轨迹数据时间问题

### ISSUE THREAD

**Issue by eugenia-cell** [wushangbin/MGFN#4]
您好，论文里面好像没有提及使用的数据集是什么时间段的，只说了是一个月份的出租车轨迹数据，能请问下具体是哪年哪个月的么？是green taxi还是yellow taxi trip呢？

**Comment by wushangbin** [comment]
为了和MVURE方法比较，而且需要精确的经纬度，用了2015年7月的数据，数据是green taxi 和 yellow taxi 合并。

**Comment by eugenia-cell** [comment]
解决了困扰我很久的问题，真的万分感谢！
________________________________
发件人: wushangbin ***@***.***>
发送时间: 2024年4月25日 4:39
收件人: wushangbin/MGFN ***@***.***>
抄送: eugenia-cell ***@***.***>; Author ***@***.***>
主题: Re: [wushangbin/MGFN] 请教轨迹数据时间问题 (Issue #4)


Closed #4<https://github.com/wushangbin/MGFN/issues/4> as completed.

―
